export const countries = [
  'Afghanistan',
  'Albania',
  'Algeria',
  'Andorra',
  'Angola',
  'Antigua and Barbuda',
  'Argentina',
  'Armenia',
  'Australia',
  'Austria',
  'Azerbaijan',
  'Bahamas',
  'Bahrain',
  'Bangladesh',
  'Barbados',
  'Belarus',
  'Belgium',
  'Belize',
  'Benin',
  'Bhutan',
  'Bolivia',
  'Bosnia and Herzegovina',
  'Botswana',
  'Brazil',
  'Brunei',
  'Bulgaria',
  'Burkina Faso',
  'Burundi',
  'Cabo Verde',
  'Cambodia',
  'Cameroon',
  'Canada',
  'Central African Republic',
  'Chad',
  'Chile',
  'China',
  'Colombia',
  'Comoros',
  'Congo',
  'Costa Rica',
  'Croatia',
  'Cuba',
  'Cyprus',
  'Czech Republic',
  'Denmark',
  'Djibouti',
  'Dominica',
  'Dominican Republic',
  'Ecuador',
  'Egypt',
  'El Salvador',
  'Equatorial Guinea',
  'Eritrea',
  'Estonia',
  'Eswatini',
  'Ethiopia',
  'Fiji',
  'Finland',
  'France',
  'Gabon',
  'Gambia',
  'Georgia',
  'Germany',
  'Ghana',
  'Greece',
  'Grenada',
  'Guatemala',
  'Guinea',
  'Guinea-Bissau',
  'Guyana',
  'Haiti',
  'Honduras',
  'Hungary',
  'Iceland',
  'India',
  'Indonesia',
  'Iran',
  'Iraq',
  'Ireland',
  'Israel',
  'Italy',
  'Jamaica',
  'Japan',
  'Jordan',
  'Kazakhstan',
  'Kenya',
  'Kiribati',
  'Korea, North',
  'Korea, South',
  'Kosovo',
  'Kuwait',
  'Kyrgyzstan',
  'Laos',
  'Latvia',
  'Lebanon',
  'Lesotho',
  'Liberia',
  'Libya',
  'Liechtenstein',
  'Lithuania',
  'Luxembourg',
  'Madagascar',
  'Malawi',
  'Malaysia',
  'Maldives',
  'Mali',
  'Malta',
  'Marshall Islands',
  'Mauritania',
  'Mauritius',
  'Mexico',
  'Micronesia',
  'Moldova',
  'Monaco',
  'Mongolia',
  'Montenegro',
  'Morocco',
  'Mozambique',
  'Myanmar',
  'Namibia',
  'Nauru',
  'Nepal',
  'Netherlands',
  'New Zealand',
  'Nicaragua',
  'Niger',
  'Nigeria',
  'North Macedonia',
  'Norway',
  'Oman',
  'Pakistan',
  'Palau',
  'Panama',
  'Papua New Guinea',
  'Paraguay',
  'Peru',
  'Philippines',
  'Poland',
  'Portugal',
  'Qatar',
  'Romania',
  'Russia',
  'Rwanda',
  'Saint Kitts and Nevis',
  'Saint Lucia',
  'Saint Vincent and the Grenadines',
  'Samoa',
  'San Marino',
  'Sao Tome and Principe',
  'Saudi Arabia',
  'Senegal',
  'Serbia',
  'Seychelles',
  'Sierra Leone',
  'Singapore',
  'Slovakia',
  'Slovenia',
  'Solomon Islands',
  'Somalia',
  'South Africa',
  'South Sudan',
  'Spain',
  'Sri Lanka',
  'Sudan',
  'Suriname',
  'Sweden',
  'Switzerland',
  'Syria',
  'Taiwan',
  'Tajikistan',
  'Tanzania',
  'Thailand',
  'Timor-Leste',
  'Togo',
  'Tonga',
  'Trinidad and Tobago',
  'Tunisia',
  'Turkey',
  'Turkmenistan',
  'Tuvalu',
  'Uganda',
  'Ukraine',
  'United Arab Emirates',
  'United Kingdom',
  'United States',
  'Uruguay',
  'Uzbekistan',
  'Vanuatu',
  'Vatican City',
  'Venezuela',
  'Vietnam',
  'Yemen',
  'Zambia',
  'Zimbabwe',
]

export const peopleData = [
  {
    id: 1,
    name: 'John Doe',
    age: 25,
    job: 'Software Engineer',
    yoe: 3,
    company: 'Tech Co',
  },
  {
    id: 2,
    name: 'Jane Smith',
    age: 28,
    job: 'Data Scientist',
    yoe: 5,
    company: 'Data Corp',
  },
  {
    id: 3,
    name: 'Bob Johnson',
    age: 30,
    job: 'Product Manager',
    yoe: 8,
    company: 'Product Innovations',
  },
  {
    id: 4,
    name: 'Emily Davis',
    age: 22,
    job: 'Frontend Developer',
    yoe: 2,
    company: 'Web Solutions',
  },
  {
    id: 5,
    name: 'Michael Brown',
    age: 35,
    job: 'Marketing Specialist',
    yoe: 7,
    company: 'Marketing Pro',
  },
  {
    id: 6,
    name: 'Jennifer Wilson',
    age: 29,
    job: 'UX Designer',
    yoe: 4,
    company: 'Design Studio',
  },
  {
    id: 7,
    name: 'Daniel Lee',
    age: 31,
    job: 'DevOps Engineer',
    yoe: 6,
    company: 'DevOps Solutions',
  },
  {
    id: 8,
    name: 'Emma Garcia',
    age: 27,
    job: 'Full Stack Developer',
    yoe: 3,
    company: 'Code Masters',
  },
  {
    id: 9,
    name: 'Christopher Taylor',
    age: 34,
    job: 'Sales Manager',
    yoe: 9,
    company: 'Sales Enterprises',
  },
  {
    id: 10,
    name: 'Olivia Miller',
    age: 26,
    job: 'Graphic Designer',
    yoe: 3,
    company: 'Creative Designs',
  },
  {
    id: 11,
    name: 'William Turner',
    age: 32,
    job: 'System Analyst',
    yoe: 5,
    company: 'Tech Innovators',
  },
  {
    id: 12,
    name: 'Sophia White',
    age: 30,
    job: 'AI Researcher',
    yoe: 7,
    company: 'AI Labs',
  },
  {
    id: 13,
    name: 'Jacob Hall',
    age: 28,
    job: 'Network Engineer',
    yoe: 4,
    company: 'Connectivity Solutions',
  },
  {
    id: 14,
    name: 'Mia Harris',
    age: 26,
    job: 'Content Creator',
    yoe: 2,
    company: 'Content Hub',
  },
  {
    id: 15,
    name: 'Ethan Martin',
    age: 33,
    job: 'Product Designer',
    yoe: 6,
    company: 'Design Innovations',
  },
  {
    id: 16,
    name: 'Ava Turner',
    age: 29,
    job: 'Quality Assurance Analyst',
    yoe: 3,
    company: 'QA Solutions',
  },
  {
    id: 17,
    name: 'Noah Scott',
    age: 27,
    job: 'UI/UX Developer',
    yoe: 4,
    company: 'Creative UI',
  },
  {
    id: 18,
    name: 'Isabella Clark',
    age: 31,
    job: 'Project Coordinator',
    yoe: 5,
    company: 'Project Management Inc',
  },
  {
    id: 19,
    name: 'Liam Adams',
    age: 25,
    job: 'Software Tester',
    yoe: 2,
    company: 'Test Solutions',
  },
  {
    id: 20,
    name: 'Avery Jenkins',
    age: 28,
    job: 'Frontend Engineer',
    yoe: 6,
    company: 'Web Innovations',
  },
  {
    id: 21,
    name: 'Ava Wilson',
    age: 31,
    job: 'Project Manager',
    yoe: 7,
    company: 'Project Solutions Inc',
  },
  {
    id: 22,
    name: 'John Doe',
    age: 25,
    job: 'Software Engineer',
    yoe: 3,
    company: 'Tech Co',
  },
  {
    id: 23,
    name: 'Jane Smith',
    age: 28,
    job: 'Data Scientist',
    yoe: 5,
    company: 'Data Corp',
  },
  {
    id: 24,
    name: 'Bob Johnson',
    age: 30,
    job: 'Product Manager',
    yoe: 8,
    company: 'Product Innovations',
  },
  {
    id: 25,
    name: 'Emily Davis',
    age: 22,
    job: 'Frontend Developer',
    yoe: 2,
    company: 'Web Solutions',
  },
  {
    id: 26,
    name: 'Michael Brown',
    age: 35,
    job: 'Marketing Specialist',
    yoe: 7,
    company: 'Marketing Pro',
  },
  {
    id: 27,
    name: 'Jennifer Wilson',
    age: 29,
    job: 'UX Designer',
    yoe: 4,
    company: 'Design Studio',
  },
  {
    id: 28,
    name: 'Daniel Lee',
    age: 31,
    job: 'DevOps Engineer',
    yoe: 6,
    company: 'DevOps Solutions',
  },
  {
    id: 29,
    name: 'Emma Garcia',
    age: 27,
    job: 'Full Stack Developer',
    yoe: 3,
    company: 'Code Masters',
  },
  {
    id: 30,
    name: 'Christopher Taylor',
    age: 34,
    job: 'Sales Manager',
    yoe: 9,
    company: 'Sales Enterprises',
  },
  {
    id: 31,
    name: 'Olivia Miller',
    age: 26,
    job: 'Graphic Designer',
    yoe: 3,
    company: 'Creative Designs',
  },
  {
    id: 32,
    name: 'William Turner',
    age: 32,
    job: 'System Analyst',
    yoe: 5,
    company: 'Tech Innovators',
  },
  {
    id: 33,
    name: 'Sophia White',
    age: 30,
    job: 'AI Researcher',
    yoe: 7,
    company: 'AI Labs',
  },
  {
    id: 34,
    name: 'Jacob Hall',
    age: 28,
    job: 'Network Engineer',
    yoe: 4,
    company: 'Connectivity Solutions',
  },
  {
    id: 35,
    name: 'Mia Harris',
    age: 26,
    job: 'Content Creator',
    yoe: 2,
    company: 'Content Hub',
  },
  {
    id: 36,
    name: 'Ethan Martin',
    age: 33,
    job: 'Product Designer',
    yoe: 6,
    company: 'Design Innovations',
  },
  {
    id: 37,
    name: 'Ava Turner',
    age: 29,
    job: 'Quality Assurance Analyst',
    yoe: 3,
    company: 'QA Solutions',
  },
  {
    id: 38,
    name: 'Noah Scott',
    age: 27,
    job: 'UI/UX Developer',
    yoe: 4,
    company: 'Creative UI',
  },
  {
    id: 39,
    name: 'Isabella Clark',
    age: 31,
    job: 'Project Coordinator',
    yoe: 5,
    company: 'Project Management Inc',
  },
  {
    id: 40,
    name: 'Liam Adams',
    age: 25,
    job: 'Software Tester',
    yoe: 2,
    company: 'Test Solutions',
  },
  {
    id: 41,
    name: 'Avery Jenkins',
    age: 28,
    job: 'Frontend Engineer',
    yoe: 6,
    company: 'Web Innovations',
  },
  {
    id: 42,
    name: 'Ava Wilson',
    age: 31,
    job: 'Project Manager',
    yoe: 7,
    company: 'Project Solutions Inc',
  },
  {
    id: 43,
    name: 'John Doe',
    age: 25,
    job: 'Software Engineer',
    yoe: 3,
    company: 'Tech Co',
  },
  {
    id: 44,
    name: 'Jane Smith',
    age: 28,
    job: 'Data Scientist',
    yoe: 5,
    company: 'Data Corp',
  },
  {
    id: 45,
    name: 'Bob Johnson',
    age: 30,
    job: 'Product Manager',
    yoe: 8,
    company: 'Product Innovations',
  },
  {
    id: 46,
    name: 'Emily Davis',
    age: 22,
    job: 'Frontend Developer',
    yoe: 2,
    company: 'Web Solutions',
  },
  {
    id: 47,
    name: 'Michael Brown',
    age: 35,
    job: 'Marketing Specialist',
    yoe: 7,
    company: 'Marketing Pro',
  },
  {
    id: 48,
    name: 'Jennifer Wilson',
    age: 29,
    job: 'UX Designer',
    yoe: 4,
    company: 'Design Studio',
  },
  {
    id: 49,
    name: 'Daniel Lee',
    age: 31,
    job: 'DevOps Engineer',
    yoe: 6,
    company: 'DevOps Solutions',
  },
  {
    id: 50,
    name: 'Emma Garcia',
    age: 27,
    job: 'Full Stack Developer',
    yoe: 3,
    company: 'Code Masters',
  },
  {
    id: 51,
    name: 'Christopher Taylor',
    age: 34,
    job: 'Sales Manager',
    yoe: 9,
    company: 'Sales Enterprises',
  },
  {
    id: 52,
    name: 'Olivia Miller',
    age: 26,
    job: 'Graphic Designer',
    yoe: 3,
    company: 'Creative Designs',
  },
  {
    id: 53,
    name: 'William Turner',
    age: 32,
    job: 'System Analyst',
    yoe: 5,
    company: 'Tech Innovators',
  },
  {
    id: 54,
    name: 'Sophia White',
    age: 30,
    job: 'AI Researcher',
    yoe: 7,
    company: 'AI Labs',
  },
  {
    id: 55,
    name: 'Jacob Hall',
    age: 28,
    job: 'Network Engineer',
    yoe: 4,
    company: 'Connectivity Solutions',
  },
  {
    id: 56,
    name: 'Mia Harris',
    age: 26,
    job: 'Content Creator',
    yoe: 2,
    company: 'Content Hub',
  },
  {
    id: 57,
    name: 'Ethan Martin',
    age: 33,
    job: 'Product Designer',
    yoe: 6,
    company: 'Design Innovations',
  },
  {
    id: 58,
    name: 'Ava Turner',
    age: 29,
    job: 'Quality Assurance Analyst',
    yoe: 3,
    company: 'QA Solutions',
  },
  {
    id: 59,
    name: 'Noah Scott',
    age: 27,
    job: 'UI/UX Developer',
    yoe: 4,
    company: 'Creative UI',
  },
  {
    id: 60,
    name: 'Isabella Clark',
    age: 31,
    job: 'Project Coordinator',
    yoe: 5,
    company: 'Project Management Inc',
  },
  {
    id: 61,
    name: 'Liam Adams',
    age: 25,
    job: 'Software Tester',
    yoe: 2,
    company: 'Test Solutions',
  },
  {
    id: 62,
    name: 'Avery Jenkins',
    age: 28,
    job: 'Frontend Engineer',
    yoe: 6,
    company: 'Web Innovations',
  },
  {
    id: 63,
    name: 'Ava Wilson',
    age: 31,
    job: 'Project Manager',
    yoe: 7,
    company: 'Project Solutions Inc',
  },
  {
    id: 64,
    name: 'John Doe',
    age: 25,
    job: 'Software Engineer',
    yoe: 3,
    company: 'Tech Co',
  },
  {
    id: 65,
    name: 'Jane Smith',
    age: 28,
    job: 'Data Scientist',
    yoe: 5,
    company: 'Data Corp',
  },
  {
    id: 66,
    name: 'Bob Johnson',
    age: 30,
    job: 'Product Manager',
    yoe: 8,
    company: 'Product Innovations',
  },
  {
    id: 67,
    name: 'Emily Davis',
    age: 22,
    job: 'Frontend Developer',
    yoe: 2,
    company: 'Web Solutions',
  },
  {
    id: 68,
    name: 'Michael Brown',
    age: 35,
    job: 'Marketing Specialist',
    yoe: 7,
    company: 'Marketing Pro',
  },
  {
    id: 69,
    name: 'Jennifer Wilson',
    age: 29,
    job: 'UX Designer',
    yoe: 4,
    company: 'Design Studio',
  },
  {
    id: 70,
    name: 'Daniel Lee',
    age: 31,
    job: 'DevOps Engineer',
    yoe: 6,
    company: 'DevOps Solutions',
  },
  {
    id: 71,
    name: 'Emma Garcia',
    age: 27,
    job: 'Full Stack Developer',
    yoe: 3,
    company: 'Code Masters',
  },
  {
    id: 72,
    name: 'Christopher Taylor',
    age: 34,
    job: 'Sales Manager',
    yoe: 9,
    company: 'Sales Enterprises',
  },
  {
    id: 73,
    name: 'Olivia Miller',
    age: 26,
    job: 'Graphic Designer',
    yoe: 3,
    company: 'Creative Designs',
  },
  {
    id: 74,
    name: 'William Turner',
    age: 32,
    job: 'System Analyst',
    yoe: 5,
    company: 'Tech Innovators',
  },
  {
    id: 75,
    name: 'Sophia White',
    age: 30,
    job: 'AI Researcher',
    yoe: 7,
    company: 'AI Labs',
  },
  {
    id: 76,
    name: 'Jacob Hall',
    age: 28,
    job: 'Network Engineer',
    yoe: 4,
    company: 'Connectivity Solutions',
  },
  {
    id: 77,
    name: 'Mia Harris',
    age: 26,
    job: 'Content Creator',
    yoe: 2,
    company: 'Content Hub',
  },
  {
    id: 78,
    name: 'Ethan Martin',
    age: 33,
    job: 'Product Designer',
    yoe: 6,
    company: 'Design Innovations',
  },
  {
    id: 79,
    name: 'Ava Turner',
    age: 29,
    job: 'Quality Assurance Analyst',
    yoe: 3,
    company: 'QA Solutions',
  },
  {
    id: 80,
    name: 'Noah Scott',
    age: 27,
    job: 'UI/UX Developer',
    yoe: 4,
    company: 'Creative UI',
  },
  {
    id: 81,
    name: 'Isabella Clark',
    age: 31,
    job: 'Project Coordinator',
    yoe: 5,
    company: 'Project Management Inc',
  },
  {
    id: 82,
    name: 'Liam Adams',
    age: 25,
    job: 'Software Tester',
    yoe: 2,
    company: 'Test Solutions',
  },
  {
    id: 83,
    name: 'Avery Jenkins',
    age: 28,
    job: 'Frontend Engineer',
    yoe: 6,
    company: 'Web Innovations',
  },
  {
    id: 84,
    name: 'Ava Wilson',
    age: 31,
    job: 'Project Manager',
    yoe: 7,
    company: 'Project Solutions Inc',
  },
  {
    id: 85,
    name: 'John Doe',
    age: 25,
    job: 'Software Engineer',
    yoe: 3,
    company: 'Tech Co',
  },
  {
    id: 86,
    name: 'Jane Smith',
    age: 28,
    job: 'Data Scientist',
    yoe: 5,
    company: 'Data Corp',
  },
  {
    id: 87,
    name: 'Bob Johnson',
    age: 30,
    job: 'Product Manager',
    yoe: 8,
    company: 'Product Innovations',
  },
  {
    id: 88,
    name: 'Emily Davis',
    age: 22,
    job: 'Frontend Developer',
    yoe: 2,
    company: 'Web Solutions',
  },
  {
    id: 89,
    name: 'Michael Brown',
    age: 35,
    job: 'Marketing Specialist',
    yoe: 7,
    company: 'Marketing Pro',
  },
  {
    id: 90,
    name: 'Jennifer Wilson',
    age: 29,
    job: 'UX Designer',
    yoe: 4,
    company: 'Design Studio',
  },
  {
    id: 91,
    name: 'Daniel Lee',
    age: 31,
    job: 'DevOps Engineer',
    yoe: 6,
    company: 'DevOps Solutions',
  },
  {
    id: 92,
    name: 'Emma Garcia',
    age: 27,
    job: 'Full Stack Developer',
    yoe: 3,
    company: 'Code Masters',
  },
  {
    id: 93,
    name: 'Christopher Taylor',
    age: 34,
    job: 'Sales Manager',
    yoe: 9,
    company: 'Sales Enterprises',
  },
  {
    id: 94,
    name: 'Olivia Miller',
    age: 26,
    job: 'Graphic Designer',
    yoe: 3,
    company: 'Creative Designs',
  },
  {
    id: 95,
    name: 'William Turner',
    age: 32,
    job: 'System Analyst',
    yoe: 5,
    company: 'Tech Innovators',
  },
  {
    id: 96,
    name: 'Sophia White',
    age: 30,
    job: 'AI Researcher',
    yoe: 7,
    company: 'AI Labs',
  },
  {
    id: 97,
    name: 'Jacob Hall',
    age: 28,
    job: 'Network Engineer',
    yoe: 4,
    company: 'Connectivity Solutions',
  },
  {
    id: 98,
    name: 'Mia Harris',
    age: 26,
    job: 'Content Creator',
    yoe: 2,
    company: 'Content Hub',
  },
  {
    id: 99,
    name: 'Ethan Martin',
    age: 33,
    job: 'Product Designer',
    yoe: 6,
    company: 'Design Innovations',
  },
  {
    id: 100,
    name: 'Ava Turner',
    age: 29,
    job: 'Quality Assurance Analyst',
    yoe: 3,
    company: 'QA Solutions',
  },
  
]